### ISSUE TITLE
TypeError: get_meta() missing 1 required positional argument: 'is_partition'

### ISSUE THREAD

**Issue by N4YC** [farhan0581/django-inspectdb-refactor#7]
`    for meta_line in self.get_meta(table_name, constraints, column_to_field_name, is_view):
TypeError: get_meta() missing 1 required positional argument: 'is_partition'
`

It doesn't works on Django 2.2 but it works on Django 2.1.

**Comment by ktaranov** [comment]
The same issue for `django 2.2.4`
```python
Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "C:\Python3\lib\site-packages\django\core\management\__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "C:\Python3\lib\site-packages\django\core\management\__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Python3\lib\site-packages\django\core\management\base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Python3\lib\site-packages\django\core\management\base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "C:\Python3\lib\site-packages\inspectdb_refactor\management\commands\inspectdb_refactor.py", line 118, in handle
    self.handle_inspection(options)
  File "C:\Python3\lib\site-packages\inspectdb_refactor\management\commands\inspectdb_refactor.py", line 270, in handle_inspection
    for meta_line in self.get_meta(table_name, constraints, column_to_field_name, is_view):
TypeError: get_meta() missing 1 required positional argument: 'is_partition'
```
